"""Application-layer protocols and use-case boundaries."""

from animated_fabric.application.import_layers import (
    IMPORT_CANVAS_MISMATCH_CODE,
    IMPORT_DIRECTION_CODE,
    IMPORT_FAILURE_CODE,
    IMPORT_MAPPING_PROPOSAL_CODE,
    ImportInspection,
    ImportLayerSet,
    ImportLimits,
    ImportResult,
    InspectedLayer,
    InspectLayerFolder,
    LayerAssignment,
    LayerImporter,
    LayerImportRequest,
    import_failure,
)
from animated_fabric.application.ports import (
    LAYER_MANIFEST_FILENAME,
    PROJECT_MANIFEST_FILENAME,
    LayerManifestRepository,
    ProjectRepository,
    RigTemplateRegistry,
)
from animated_fabric.application.render_cache import RenderComputationCache
from animated_fabric.application.render_frame import (
    RENDER_FAILURE_CODE,
    RenderFrame,
    render_failure,
)
from animated_fabric.application.rendering import (
    ClippingEdges,
    CompositedFrame,
    CompositeRequest,
    FrameCompositor,
    PlannedRenderLayer,
    RenderedFrame,
    Renderer,
    RenderPlanner,
    RenderProject,
    RenderQuality,
    RenderRequest,
)
from animated_fabric.application.validation_service import ValidateProject, ValidateProjectRequest

__all__ = [
    "ClippingEdges",
    "CompositedFrame",
    "CompositeRequest",
    "FrameCompositor",
    "IMPORT_CANVAS_MISMATCH_CODE",
    "IMPORT_DIRECTION_CODE",
    "IMPORT_FAILURE_CODE",
    "IMPORT_MAPPING_PROPOSAL_CODE",
    "ImportInspection",
    "ImportLayerSet",
    "ImportLimits",
    "ImportResult",
    "InspectedLayer",
    "InspectLayerFolder",
    "LAYER_MANIFEST_FILENAME",
    "LayerManifestRepository",
    "LayerAssignment",
    "LayerImporter",
    "LayerImportRequest",
    "PROJECT_MANIFEST_FILENAME",
    "PlannedRenderLayer",
    "ProjectRepository",
    "RigTemplateRegistry",
    "RENDER_FAILURE_CODE",
    "RenderComputationCache",
    "RenderFrame",
    "RenderedFrame",
    "Renderer",
    "RenderPlanner",
    "RenderProject",
    "RenderQuality",
    "RenderRequest",
    "ValidateProject",
    "ValidateProjectRequest",
    "import_failure",
    "render_failure",
]
