-keep class com.caatuu.android.StoreMvpBridge { *; }
-keep class com.caatuu.android.CaatuuAssetClient { *; }
-keep class com.caatuu.android.VectorDatabaseManager { *; }
-keep class com.caatuu.android.DictionaryManager { *; }
-keep class com.caatuu.android.StaticAssetManager { *; }
