"""Public domain contracts for Animated Fabric."""

from animated_fabric.domain._base import (
    DomainModel,
    JsonValue,
    ProjectPath,
    SchemaVersion,
    SemanticId,
    Sha256Digest,
)
from animated_fabric.domain.animation import (
    AnimationClip,
    AnimationEvent,
    AnimationTrack,
    AnimationValue,
    EventId,
    GeneratorProvenance,
    Interpolation,
    Keyframe,
    TargetType,
    TrackProperty,
    ValueMode,
)
from animated_fabric.domain.animation_evaluator import (
    AnimationEvaluator,
    EvaluatedAnimation,
    EvaluatedPartState,
)
from animated_fabric.domain.assets import AssetLayer, LayerManifest
from animated_fabric.domain.diagnostics import Diagnostic, OperationResult, Severity
from animated_fabric.domain.exceptions import (
    AnimatedFabricError,
    AnimationError,
    AssetImportError,
    ExportError,
    ProjectValidationError,
    ProjectValidationKind,
    ProjectVersionError,
    RenderError,
    RigDefinitionError,
)
from animated_fabric.domain.export import ExportProfile
from animated_fabric.domain.geometry import IntPoint, IntSize, SelectionEllipse, Transform2D, Vec2
from animated_fabric.domain.hierarchy import (
    topological_bone_order,
    validate_topological_bone_order,
)
from animated_fabric.domain.interpolation import evaluate_track, normalize_clip_time
from animated_fabric.domain.pose import (
    PoseResolver,
    ResolvedPose,
    bone_local_matrix,
    combine_bone_transform,
    part_pivot_for_direction,
    part_to_canvas_matrix,
    socket_to_canvas_matrix,
)
from animated_fabric.domain.project import (
    CanvasDefinition,
    Direction,
    DirectionDefinition,
    DirectionMode,
    PixelSnap,
    ProjectManifest,
    ProjectSlug,
)
from animated_fabric.domain.rig import (
    BoneDefinition,
    DirectionProfile,
    PartBinding,
    RigDefinition,
    SocketDefinition,
)
from animated_fabric.domain.transforms import (
    Matrix3,
    identity_matrix,
    multiply_matrices,
    rotation_matrix,
    scale_matrix,
    transform_matrix,
    transform_point,
    translation_matrix,
)
from animated_fabric.domain.validation import (
    AnimationDocument,
    AssetObservation,
    ProjectValidator,
    ValidationCode,
    ValidationInput,
    resolve_draw_order,
)

__all__ = [
    "AnimatedFabricError",
    "AnimationClip",
    "AnimationDocument",
    "AnimationError",
    "AnimationEvent",
    "AnimationEvaluator",
    "AnimationTrack",
    "AnimationValue",
    "AssetImportError",
    "AssetLayer",
    "AssetObservation",
    "BoneDefinition",
    "CanvasDefinition",
    "Diagnostic",
    "Direction",
    "DirectionDefinition",
    "DirectionMode",
    "DirectionProfile",
    "DomainModel",
    "EventId",
    "EvaluatedAnimation",
    "EvaluatedPartState",
    "ExportError",
    "ExportProfile",
    "GeneratorProvenance",
    "IntPoint",
    "IntSize",
    "Interpolation",
    "JsonValue",
    "Keyframe",
    "LayerManifest",
    "Matrix3",
    "OperationResult",
    "PartBinding",
    "PixelSnap",
    "PoseResolver",
    "ProjectManifest",
    "ProjectPath",
    "ProjectSlug",
    "ProjectValidator",
    "ProjectValidationError",
    "ProjectValidationKind",
    "ProjectVersionError",
    "RenderError",
    "RigDefinition",
    "RigDefinitionError",
    "ResolvedPose",
    "SchemaVersion",
    "SelectionEllipse",
    "SemanticId",
    "Severity",
    "Sha256Digest",
    "SocketDefinition",
    "TargetType",
    "TrackProperty",
    "Transform2D",
    "ValueMode",
    "ValidationCode",
    "ValidationInput",
    "Vec2",
    "bone_local_matrix",
    "combine_bone_transform",
    "evaluate_track",
    "identity_matrix",
    "multiply_matrices",
    "normalize_clip_time",
    "part_to_canvas_matrix",
    "part_pivot_for_direction",
    "resolve_draw_order",
    "rotation_matrix",
    "scale_matrix",
    "socket_to_canvas_matrix",
    "topological_bone_order",
    "validate_topological_bone_order",
    "transform_matrix",
    "transform_point",
    "translation_matrix",
]
