-keep class com.caatuu.android.ProductBridge { *; }
-keep class com.caatuu.android.AppUpdateManager { *; }
-keep class com.caatuu.android.CaatuuAssetClient { *; }
-keep class com.caatuu.android.VectorDatabaseManager { *; }
-keep class com.caatuu.android.DictionaryManager { *; }
-keep class com.caatuu.android.AndroidSpeechManager { *; }
-keep class com.caatuu.android.StaticAssetManager { *; }
